---
app_dir: app

API_KEY: xltG4HvdQzsRUlObmjJYdewx8
API_SECRET_KEY: 06TWFbHup9dgNEMR0izqxdNVYHFZ461UFIzwbuL1thHYzBit9h
ACESS_TOKEN: 2207370697-TeOgxlvJJfdR6GeygOIu2B9NiJP47AXB2jFtxY5
ACESS_TOKEN_SECRET: Ty7KDfVbfuXxcTKwOaizIIP1rjn2orYlH32w6Gx72tQWF