---
app_dir: app

API_KEY: fote8GtC3mCBc34c736uWhZ38
API_SECRET_KEY: 0dyh87kkxw6DildE5ZM0FkDHE1x9hghTWR1yq4xmo39hXBOcgV
ACESS_TOKEN: 1390939348493737986-V9Lddu48cRYEzvyJyUCaLtRnGiCvgx
ACESS_TOKEN_SECRET: tkBMa3PLjhz1LFucCofZWF88G9EdwZ8iriZ7sGhA6gBq7