version: "3.9"
services:
    # couchdb:
    #     image: bitnami/couchdb
    #     restart: always
    #     ports:
    #         - "5984:5984"

    harvestor:
        build: tweet-harvestor-docker
        restart: always
        environment: 
            API_KEY: fJdaD97jmlFIR8JHyYx7MdAQu
            API_SECRET_KEY: Eung9Z69wga64EmmqxSPdZCkU0qpyrxKH114PdZeicdcPzSyfo
            ACESS_TOKEN: 2207370697-CNsx9avZawfNHjTSBvblXUFI2jvN6CTu1UdDlhG
            ACESS_TOKEN_SECRET: ilpswPQcTjVRYQ7A4VqdpCPetIhWPf7cQKjhV37UwTo15
            SERVER_USERNAME: admin
            SERVER_PASSWORD: couchdb
            SERVER_ADDRESS: "http://couchdb:5984"