version: "3.9"
services:
    # couchdb:
    #     image: bitnami/couchdb
    #     restart: always
    #     ports:
    #         - "5984:5984"

    harvestor:
        build: tweet-harvestor-docker
        restart: always
        environment: 
            API_KEY: fote8GtC3mCBc34c736uWhZ38
            API_SECRET_KEY: 0dyh87kkxw6DildE5ZM0FkDHE1x9hghTWR1yq4xmo39hXBOcgV
            ACESS_TOKEN: 1390939348493737986-V9Lddu48cRYEzvyJyUCaLtRnGiCvgx
            ACESS_TOKEN_SECRET: tkBMa3PLjhz1LFucCofZWF88G9EdwZ8iriZ7sGhA6gBq7
            SERVER_USERNAME: admin
            SERVER_PASSWORD: couchdb
            SERVER_ADDRESS: "http://couchdb:5984"