version: "3.9"
services:
    couchdb:
        image: bitnami/couchdb
        restart: always
        ports:
            - "5984:5984"

    harvestor:
        build: tweet-harvestor-docker
        restart: always
        environment: 
            API_KEY: xltG4HvdQzsRUlObmjJYdewx8
            API_SECRET_KEY: 06TWFbHup9dgNEMR0izqxdNVYHFZ461UFIzwbuL1thHYzBit9h
            ACESS_TOKEN: 2207370697-TeOgxlvJJfdR6GeygOIu2B9NiJP47AXB2jFtxY5
            ACESS_TOKEN_SECRET: Ty7KDfVbfuXxcTKwOaizIIP1rjn2orYlH32w6Gx72tQWF
            SERVER_USERNAME: admin
            SERVER_PASSWORD: couchdb
            SERVER_IP: couchdb

    flask:
        build: flask-docker
        restart: always
        ports: 
            - "5000:5000"
        environment:
            SERVER_IP: couchdb
            COUCHDB_AUTH_TOKEN: ZWZ3ZWZ3ZWZld2V3cjM6aTM5MmZiMzlmYjI5M2Ziam5ubA==